FROM openhd/2018-10-09-raspbian-stretch-lite:v1  

COPY .git /data/.git/
COPY i2c_cmd /data/i2c_cmd/
COPY veye_raspcam /data/veye_raspcam/
COPY package.sh /data/

RUN apt update

RUN apt -y install git

RUN apt -y install ruby-dev

RUN apt -y install python-pip

RUN apt -y purge python-configparser

RUN gem install fpm

RUN pip install cloudsmith-cli

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh pi stretch docker
