FROM ghcr.io/openhd/bullseye-lite:v2.4

RUN apt-get update --allow-releaseinfo-change

RUN apt install -y gcc libc6-dev libraspberrypi-dev raspberrypi-kernel-headers

COPY .git /data/.git/
COPY i2c_cmd /data/i2c_cmd/
COPY package.sh /data/

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh armhf raspbian bullseye docker
