FROM openhd/2020-05-27-raspios-buster-lite-armhf:v1

RUN apt update

RUN apt -y install git

RUN apt -y install ruby-dev

RUN apt -y install python3-pip

RUN apt -y purge python-configparser

RUN gem install fpm

RUN pip3 install cloudsmith-cli

COPY .git /data/.git/
COPY i2c_cmd /data/i2c_cmd/
COPY veye_raspcam /data/veye_raspcam/
COPY package.sh /data/

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh pi buster docker
